/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        background: 'var(--color-background)',
        canvas: 'var(--color-background)',
        surface: 'var(--color-surface)',
        'surface-subtle': 'var(--color-surface-subtle)',
        'surface-strong': 'var(--color-surface-strong)',
        'surface-hover': 'var(--color-surface-hover)',
        border: 'var(--color-border)',
        'border-strong': 'var(--color-border-strong)',
        charcoal: {
          DEFAULT: 'var(--color-text-primary)',
          muted: 'var(--color-text-secondary)',
        },
        'text-primary': 'var(--color-text-primary)',
        'text-secondary': 'var(--color-text-secondary)',
        'text-muted': 'var(--color-text-muted)',
        'carbon-gray-100': 'var(--color-gray-100)',
        'carbon-gray-90': 'var(--color-gray-90)',
        'carbon-gray-80': 'var(--color-gray-80)',
        'carbon-gray-70': 'var(--color-gray-70)',
        'carbon-gray-60': 'var(--color-gray-60)',
        'carbon-gray-50': 'var(--color-gray-50)',
        'carbon-gray-30': 'var(--color-gray-30)',
        'carbon-gray-20': 'var(--color-gray-20)',
        'carbon-gray-10': 'var(--color-gray-10)',
        primary: {
          50: 'var(--color-primary-50)',
          100: 'var(--color-primary-100)',
          200: 'var(--color-primary-200)',
          300: 'var(--color-primary-300)',
          400: 'var(--color-primary-400)',
          500: 'var(--color-primary-500)',
          600: 'var(--color-primary-600)',
          700: 'var(--color-primary-700)',
          800: 'var(--color-primary-800)',
          900: 'var(--color-primary-900)',
        },
        success: 'var(--color-success)',
        warning: 'var(--color-warning)',
        'warning-strong': 'var(--color-warning-strong)',
        danger: 'var(--color-danger)',
        info: 'var(--color-info)',
      },
      fontFamily: {
        sans: ['"IBM Plex Sans"', 'Inter', 'system-ui', '-apple-system', 'sans-serif'],
      },
      fontSize: {
        display: '48px',
        'heading-xl': '32px',
        'heading-lg': '28px',
        'heading-md': '20px',
        'heading-sm': '16px',
      },
      boxShadow: {
        card: '0 1px 2px 0 rgba(0, 0, 0, 0.05)',
        carbon: '0 2px 6px 0 rgba(0, 0, 0, 0.1)',
      },
    },
  },
  plugins: [],
}